# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# Add homebrew completions
# This needs to be done befor calling compinit, so before loading zgenom
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# load zgenom https://github.com/jandamm/zgenom
source "${HOME}/.zgenom/zgenom.zsh"

# Check for plugin and zgenom updates every 7 days
# This does not increase the startup time.
zgenom autoupdate

# if the init script doesn't exist
# After modifying this block run `zgenom reset` and then restart the shell
if ! zgenom saved; then
    echo "Creating a zgenom save"

    # Add this if you experience issues with missing completions or errors mentioning compdef.
    zgenom compdef

    zgenom load zsh-users/zsh-syntax-highlighting

    # completions
    zgenom load zsh-users/zsh-completions

    # https://github.com/zsh-users/zsh-autosuggestions
    zgenom load zsh-users/zsh-autosuggestions

    # https://github.com/ael-code/zsh-colored-man-pages
    zgenom load ael-code/zsh-colored-man-pages

    # https://github.com/zpm-zsh/colorize
    zgenom load zpm-zsh/colorize

    # https://github.com/zdharma-continuum/zsh-navigation-tools
    zgenom load zdharma-continuum/zsh-navigation-tools

    # https://github.com/zsh-users/zsh-history-substring-search
    zgenom load zsh-users/zsh-history-substring-search

    # https://github.com/rupa/z
    zgenom load rupa/z

    # theme
    zgenom load romkatv/powerlevel10k powerlevel10k

    # save all to init script
    zgenom save

    # Compile your zsh files
    zgenom compile "$HOME/.zshrc"
    # zgenom compile $ZDOTDIR

    # You can perform other "time consuming" maintenance tasks here as well.
    # If you use `zgenom autoupdate` you're making sure it gets
    # executed every 7 days.

    # rbenv rehash
fi

# Disable autosugest if pasting more than 20 characters
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

# history substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

alias ls='ls -G --color=auto'
alias ipv6_on='networksetup -setv6automatic "Wi-Fi"'
alias ipv6_off='networksetup -setv6off "Wi-Fi"'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# load local .zshrc customizations
[[ ! -f ~/.zshrc.local ]] || source ~/.zshrc.local

# Some special completions
autoload bashcompinit && bashcompinit
eval "$(op completion zsh)"; compdef _op op

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export NODE_VERSIONS="/Users/kahokas/.nvm/versions/node"
export NODE_VERSION_PREFIX="v"
if type direnv &>/dev/null; then
    eval "$(direnv hook zsh)"
fi

jdk() {
    version=$1
    export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
    java -version
}

# https://www.soberkoder.com/better-zsh-history/
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
