# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="kimia"
DEFAULT_USER="kimia"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias rmDS='find . \( -name ".DS_Store" -o -name "._.DS_Store" \) -exec rm -vr {} \;'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"


WORKON_HOME="$HOME/virtualenv"
DISABLE_VENV_CD=1
if [[ ! -d $WORKON_HOME ]]; then
    echo "Creating directory $WORKON_HOME"
    mkdir $WORKON_HOME
fi

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Override this in zshrc.local
plugins=(colored-man git gitignore virtualenvwrapper)

export EDITOR=nano
export VISUAL=nano

if [[ -d $HOME/bin ]];then
    PATH=$PATH:$HOME/bin
fi
# Add RVM to PATH for scripting
if [[ -d $HOME/.rvm ]]; then
    PATH=$PATH:$HOME/.rvm/bin
fi

# Finally, source per-host config and oh-my-zsh
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
source $ZSH/oh-my-zsh.sh

